-- Seed: commodity names (en / hi / mr) and Maharashtra district neighbours

insert into public.commodities (data_name, name_en, name_hi, name_mr, aliases, is_quick_pick) values
  ('Onion', 'Onion', 'प्याज', 'कांदा', '{kanda,pyaj,pyaaz,kande,कांदे}', true),
  ('Tomato', 'Tomato', 'टमाटर', 'टोमॅटो', '{tamatar,tamater,tomatoes}', true),
  ('Potato', 'Potato', 'आलू', 'बटाटा', '{aloo,alu,batata,potatoes}', true),
  ('Wheat', 'Wheat', 'गेहूं', 'गहू', '{gehu,gehun,gahu}', true),
  ('Soyabean', 'Soybean', 'सोयाबीन', 'सोयाबीन', '{soybean,soya,soyabin}', true),
  ('Brinjal', 'Brinjal', 'बैंगन', 'वांगी', '{baingan,vangi,wangi,eggplant}', false),
  ('Cotton', 'Cotton', 'कपास', 'कापूस', '{kapas,kapus}', false),
  ('Tur (Arhar)', 'Tur (Arhar)', 'अरहर / तुअर', 'तूर', '{tur,toor,arhar,tuar}', false),
  ('Bengal Gram(Gram)(Whole)', 'Chana (Gram)', 'चना', 'हरभरा', '{chana,gram,harbhara}', false),
  ('Green Gram (Moong)(Whole)', 'Moong', 'मूंग', 'मूग', '{moong,mung}', false),
  ('Black Gram (Urd Beans)(Whole)', 'Urad', 'उड़द', 'उडीद', '{urad,udid}', false),
  ('Jowar(Sorghum)', 'Jowar', 'ज्वार', 'ज्वारी', '{jowar,jwari,sorghum}', false),
  ('Bajra(Pearl Millet/Cumbu)', 'Bajra', 'बाजरा', 'बाजरी', '{bajra,bajri}', false),
  ('Maize', 'Maize', 'मक्का', 'मका', '{makka,maka,corn}', false),
  ('Paddy(Dhan)(Common)', 'Paddy', 'धान', 'भात', '{dhan,paddy,bhat}', false),
  ('Rice', 'Rice', 'चावल', 'तांदूळ', '{chawal,tandul}', false),
  ('Groundnut', 'Groundnut', 'मूंगफली', 'भुईमूग', '{mungfali,bhuimug,peanut}', false),
  ('Sugarcane', 'Sugarcane', 'गन्ना', 'ऊस', '{ganna,us}', false),
  ('Cabbage', 'Cabbage', 'पत्ता गोभी', 'कोबी', '{kobi,patta gobhi}', false),
  ('Cauliflower', 'Cauliflower', 'फूलगोभी', 'फ्लॉवर', '{phool gobhi,gobi,flower}', false),
  ('Green Chilli', 'Green Chilli', 'हरी मिर्च', 'हिरवी मिरची', '{mirchi,mirch,chilli}', false),
  ('Ladies Finger', 'Okra (Bhindi)', 'भिंडी', 'भेंडी', '{bhindi,bhendi,okra}', false),
  ('Bitter gourd', 'Bitter Gourd', 'करेला', 'कारले', '{karela,karle}', false),
  ('Bottle gourd', 'Bottle Gourd', 'लौकी', 'दुधी भोपळा', '{lauki,dudhi}', false),
  ('Cucumbar(Kheera)', 'Cucumber', 'खीरा', 'काकडी', '{kheera,kakdi,cucumber}', false),
  ('Carrot', 'Carrot', 'गाजर', 'गाजर', '{gajar}', false),
  ('Garlic', 'Garlic', 'लहसुन', 'लसूण', '{lahsun,lasun}', false),
  ('Ginger(Green)', 'Ginger', 'अदरक', 'आले', '{adrak,ale}', false),
  ('Coriander(Leaves)', 'Coriander Leaves', 'धनिया पत्ती', 'कोथिंबीर', '{dhaniya,kothimbir}', false),
  ('Methi(Leaves)', 'Fenugreek Leaves', 'मेथी', 'मेथी', '{methi}', false),
  ('Spinach', 'Spinach', 'पालक', 'पालक', '{palak}', false),
  ('Peas Wet', 'Green Peas', 'हरी मटर', 'वाटाणा', '{matar,vatana}', false),
  ('Cluster beans', 'Cluster Beans', 'ग्वार फली', 'गवार', '{gavar,guar}', false),
  ('Capsicum', 'Capsicum', 'शिमला मिर्च', 'ढोबळी मिरची', '{shimla mirch,dhobli}', false),
  ('Pomegranate', 'Pomegranate', 'अनार', 'डाळिंब', '{anar,dalimb}', false),
  ('Banana', 'Banana', 'केला', 'केळी', '{kela,keli}', false),
  ('Grapes', 'Grapes', 'अंगूर', 'द्राक्षे', '{angoor,draksh}', false),
  ('Mango', 'Mango', 'आम', 'आंबा', '{aam,amba}', false),
  ('Orange', 'Orange', 'संतरा', 'संत्री', '{santra,santri}', false),
  ('Lemon', 'Lemon', 'नींबू', 'लिंबू', '{nimbu,limbu}', false),
  ('Papaya', 'Papaya', 'पपीता', 'पपई', '{papita,papai}', false),
  ('Water Melon', 'Watermelon', 'तरबूज', 'कलिंगड', '{tarbuj,kalingad}', false),
  ('Turmeric', 'Turmeric', 'हल्दी', 'हळद', '{haldi,halad}', false)
on conflict (data_name) do nothing;

-- District neighbours (both directions are inserted below)
with pairs(a, b) as (values
  ('Mumbai', 'Mumbai Suburban'), ('Mumbai', 'Thane'), ('Mumbai', 'Raigad'),
  ('Mumbai Suburban', 'Thane'), ('Mumbai Suburban', 'Raigad'),
  ('Thane', 'Palghar'), ('Thane', 'Raigad'), ('Thane', 'Pune'), ('Thane', 'Nashik'), ('Thane', 'Ahmednagar'),
  ('Palghar', 'Nashik'),
  ('Raigad', 'Pune'), ('Raigad', 'Ratnagiri'), ('Raigad', 'Satara'),
  ('Pune', 'Ahmednagar'), ('Pune', 'Satara'), ('Pune', 'Solapur'),
  ('Nashik', 'Ahmednagar'), ('Nashik', 'Dhule'), ('Nashik', 'Jalgaon'), ('Nashik', 'Aurangabad'),
  ('Ahmednagar', 'Aurangabad'), ('Ahmednagar', 'Beed'), ('Ahmednagar', 'Solapur'), ('Ahmednagar', 'Osmanabad'),
  ('Satara', 'Sangli'), ('Satara', 'Solapur'), ('Satara', 'Ratnagiri'),
  ('Sangli', 'Kolhapur'), ('Sangli', 'Solapur'), ('Sangli', 'Ratnagiri'),
  ('Kolhapur', 'Ratnagiri'), ('Kolhapur', 'Sindhudurg'),
  ('Ratnagiri', 'Sindhudurg'),
  ('Solapur', 'Osmanabad'), ('Solapur', 'Latur'),
  ('Aurangabad', 'Jalgaon'), ('Aurangabad', 'Jalna'), ('Aurangabad', 'Beed'), ('Aurangabad', 'Buldhana'),
  ('Jalgaon', 'Dhule'), ('Jalgaon', 'Buldhana'),
  ('Dhule', 'Nandurbar'),
  ('Jalna', 'Beed'), ('Jalna', 'Parbhani'), ('Jalna', 'Buldhana'),
  ('Beed', 'Osmanabad'), ('Beed', 'Latur'), ('Beed', 'Parbhani'),
  ('Osmanabad', 'Latur'),
  ('Latur', 'Nanded'), ('Latur', 'Parbhani'),
  ('Parbhani', 'Hingoli'), ('Parbhani', 'Nanded'),
  ('Hingoli', 'Nanded'), ('Hingoli', 'Washim'), ('Hingoli', 'Yavatmal'),
  ('Nanded', 'Yavatmal'),
  ('Buldhana', 'Akola'), ('Buldhana', 'Washim'),
  ('Akola', 'Washim'), ('Akola', 'Amravati'),
  ('Washim', 'Yavatmal'), ('Washim', 'Amravati'),
  ('Amravati', 'Yavatmal'), ('Amravati', 'Wardha'), ('Amravati', 'Nagpur'),
  ('Yavatmal', 'Wardha'), ('Yavatmal', 'Chandrapur'),
  ('Wardha', 'Nagpur'), ('Wardha', 'Chandrapur'),
  ('Nagpur', 'Bhandara'), ('Nagpur', 'Chandrapur'),
  ('Bhandara', 'Gondia'), ('Bhandara', 'Chandrapur'),
  ('Gondia', 'Gadchiroli'),
  ('Chandrapur', 'Gadchiroli')
)
insert into public.district_neighbours (district, neighbour)
select a, b from pairs
union
select b, a from pairs
on conflict do nothing;
